In [1]:
from algos.II import iterative_improvement
algo_energy = []
solution_energy = []
pg_energy = []

solution_cost = []
pg_cost = []

solution_latency = []
pg_latency = []


query_names = ['3b','1a','32a','8a','7a','25a','19a','22a','24a','28a','29b']


for query in query_names:
    print("----------------------------------------------------------")
    print(query)
    with open('/home/said/Desktop/projects/job_algos/JOB-queries/'+ str(query) + '.sql', 'r') as file:

        query = file.read()

        solution , cost = iterative_improvement(query, 3)
        solution_cost.append(cost)

    print(solution_cost)

----------------------------------------------------------
3b
mother loop index 1
mother loop index 2
mother loop index 3
best join order:  [{'value': 'keyword', 'name': 'k'}, {'value': 'movie_info', 'name': 'mi'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'title', 'name': 't'}]
[34228.3]
----------------------------------------------------------
1a
mother loop index 1
mother loop index 2
mother loop index 3
best join order:  [{'value': 'company_type', 'name': 'ct'}, {'value': 'info_type', 'name': 'it'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'movie_info_idx', 'name': 'mi_idx'}, {'value': 'title', 'name': 't'}]
[34228.3, 19966.0]
----------------------------------------------------------
32a
mother loop index 1
current neighbor_cost:  5478.94
current best_cost:  5478.94
mother loop index 2
current neighbor_cost:  5478.94
current neighbor_cost:  5478.92
current best_cost:  5478.92
mother loop index 3
best join order:  [{'value': 'movie_link', 'name': 'ml'}, {'value': 'link_type', 'name': 'lt'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'keyword', 'name': 'k'}, {'value': 'title', 'name': 't2'}, {'value': 'title', 'name': 't1'}]
[34228.3, 19966.0, 5478.92]
----------------------------------------------------------
8a
mother loop index 1
mother loop index 2
mother loop index 3
best join order:  [{'value': 'aka_name', 'name': 'an1'}, {'value': 'cast_info', 'name': 'ci'}, {'value': 'company_name', 'name': 'cn'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'name', 'name': 'n1'}, {'value': 'role_type', 'name': 'rt'}, {'value': 'title', 'name': 't'}]
[34228.3, 19966.0, 5478.92, 62253.63]
----------------------------------------------------------
7a
mother loop index 1
current neighbor_cost:  14265.9
current best_cost:  14265.9
mother loop index 2
current neighbor_cost:  14265.9
current neighbor_cost:  13388.61
current best_cost:  13388.61
mother loop index 3
current neighbor_cost:  14265.9
current neighbor_cost:  13388.61
best join order:  [{'value': 'title', 'name': 't'}, {'value': 'cast_info', 'name': 'ci'}, {'value': 'info_type', 'name': 'it'}, {'value': 'link_type', 'name': 'lt'}, {'value': 'movie_link', 'name': 'ml'}, {'value': 'name', 'name': 'n'}, {'value': 'aka_name', 'name': 'an'}, {'value': 'person_info', 'name': 'pi'}]
[34228.3, 19966.0, 5478.92, 62253.63, 13388.61]
----------------------------------------------------------
25a
mother loop index 1
mother loop index 2
mother loop index 3
best join order:  [{'value': 'cast_info', 'name': 'ci'}, {'value': 'info_type', 'name': 'it1'}, {'value': 'info_type', 'name': 'it2'}, {'value': 'keyword', 'name': 'k'}, {'value': 'movie_info', 'name': 'mi'}, {'value': 'movie_info_idx', 'name': 'mi_idx'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'name', 'name': 'n'}, {'value': 'title', 'name': 't'}]
[34228.3, 19966.0, 5478.92, 62253.63, 13388.61, 15862.63]
----------------------------------------------------------
19a
mother loop index 1
mother loop index 2
mother loop index 3
best join order:  [{'value': 'aka_name', 'name': 'an'}, {'value': 'char_name', 'name': 'chn'}, {'value': 'cast_info', 'name': 'ci'}, {'value': 'company_name', 'name': 'cn'}, {'value': 'info_type', 'name': 'it'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'movie_info', 'name': 'mi'}, {'value': 'name', 'name': 'n'}, {'value': 'role_type', 'name': 'rt'}, {'value': 'title', 'name': 't'}]
[34228.3, 19966.0, 5478.92, 62253.63, 13388.61, 15862.63, 67849.34]
----------------------------------------------------------
22a
mother loop index 1
mother loop index 2
mother loop index 3
best join order:  [{'value': 'company_name', 'name': 'cn'}, {'value': 'company_type', 'name': 'ct'}, {'value': 'info_type', 'name': 'it1'}, {'value': 'info_type', 'name': 'it2'}, {'value': 'keyword', 'name': 'k'}, {'value': 'kind_type', 'name': 'kt'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'movie_info', 'name': 'mi'}, {'value': 'movie_info_idx', 'name': 'mi_idx'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'title', 'name': 't'}]
[34228.3, 19966.0, 5478.92, 62253.63, 13388.61, 15862.63, 67849.34, 13243.08]
----------------------------------------------------------
24a
mother loop index 1
current neighbor_cost:  10554.97
current best_cost:  10554.97
mother loop index 2
current neighbor_cost:  10551.65
current best_cost:  10551.65
mother loop index 3
current neighbor_cost:  10552.32
current neighbor_cost:  10550.32
current best_cost:  10550.32
best join order:  [{'value': 'name', 'name': 'n'}, {'value': 'char_name', 'name': 'chn'}, {'value': 'cast_info', 'name': 'ci'}, {'value': 'company_name', 'name': 'cn'}, {'value': 'info_type', 'name': 'it'}, {'value': 'keyword', 'name': 'k'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'movie_info', 'name': 'mi'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'role_type', 'name': 'rt'}, {'value': 'aka_name', 'name': 'an'}, {'value': 'title', 'name': 't'}]
[34228.3, 19966.0, 5478.92, 62253.63, 13388.61, 15862.63, 67849.34, 13243.08, 10550.32]
----------------------------------------------------------
28a
mother loop index 1
current neighbor_cost:  9923.37
current best_cost:  9923.37
mother loop index 2
current neighbor_cost:  9914.58
current best_cost:  9914.58
mother loop index 3
current neighbor_cost:  9914.58
best join order:  [{'value': 'comp_cast_type', 'name': 'cct2'}, {'value': 'comp_cast_type', 'name': 'cct1'}, {'value': 'complete_cast', 'name': 'cc'}, {'value': 'company_name', 'name': 'cn'}, {'value': 'company_type', 'name': 'ct'}, {'value': 'info_type', 'name': 'it1'}, {'value': 'info_type', 'name': 'it2'}, {'value': 'keyword', 'name': 'k'}, {'value': 'kind_type', 'name': 'kt'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'movie_info', 'name': 'mi'}, {'value': 'movie_info_idx', 'name': 'mi_idx'}, {'value': 'title', 'name': 't'}, {'value': 'movie_keyword', 'name': 'mk'}]
[34228.3, 19966.0, 5478.92, 62253.63, 13388.61, 15862.63, 67849.34, 13243.08, 10550.32, 9914.58]
----------------------------------------------------------
29b
mother loop index 1
current neighbor_cost:  5379.7
current best_cost:  5379.7
mother loop index 2
current neighbor_cost:  5377.96
current best_cost:  5377.96
mother loop index 3
current neighbor_cost:  5377.9
current best_cost:  5377.9
best join order:  [{'value': 'aka_name', 'name': 'an'}, {'value': 'complete_cast', 'name': 'cc'}, {'value': 'comp_cast_type', 'name': 'cct1'}, {'value': 'comp_cast_type', 'name': 'cct2'}, {'value': 'char_name', 'name': 'chn'}, {'value': 'cast_info', 'name': 'ci'}, {'value': 'company_name', 'name': 'cn'}, {'value': 'role_type', 'name': 'rt'}, {'value': 'info_type', 'name': 'it3'}, {'value': 'keyword', 'name': 'k'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'movie_info', 'name': 'mi'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'name', 'name': 'n'}, {'value': 'info_type', 'name': 'it'}, {'value': 'person_info', 'name': 'pi'}, {'value': 'title', 'name': 't'}]
[34228.3, 19966.0, 5478.92, 62253.63, 13388.61, 15862.63, 67849.34, 13243.08, 10550.32, 9914.58, 5377.9]