In [1]:
import csv
from algos.helper_functions import create_file, get_query_latency
from energy.energy_functions import *
from algos.SA import simulated_annealing
solutions = []
algo_energy = []
solution_energy = []
pg_energy = []

solution_cost = []
pg_cost = []

solution_latency = []
pg_latency = []

algo_metadata={}

# Set the path to the directory containing the files
directory_path = "JOB-queries"


# Loop over all the files in the directory
for filename in os.listdir(directory_path):

    # Check if the file is a file and not a directory
    if os.path.isfile(os.path.join(directory_path, filename)) :  # and filename in elements:
        # Open the file for reading
        with open(os.path.join(directory_path, filename), 'r', encoding="utf8") as file:
            # Read the contents of the file
            query = file.read()

            #apply the algorithm
            solution, cost = simulated_annealing(query, 10, 8, 0.5)



        print("solution_cost : ", solution_cost)

------------------------------------------------
current join order:  [{'value': 'link_type', 'name': 'lt'}, {'value': 'keyword', 'name': 'k'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'movie_link', 'name': 'ml'}, {'value': 'title', 'name': 't1'}, {'value': 'title', 'name': 't2'}]
current join order cost:  5478.94
------------------------------------------------
best cost 5478.94
------------------------------------------------
current join order:  [{'value': 'link_type', 'name': 'lt'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'keyword', 'name': 'k'}, {'value': 'movie_link', 'name': 'ml'}, {'value': 'title', 'name': 't1'}, {'value': 'title', 'name': 't2'}]
current join order cost:  5478.94
------------------------------------------------
------------------------------------------------
current join order:  [{'value': 'title', 'name': 't2'}, {'value': 'title', 'name': 't1'}, {'value': 'movie_link', 'name': 'ml'}, {'value': 'keyword', 'name': 'k'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'link_type', 'name': 'lt'}]
current join order cost:  5269.85
------------------------------------------------
best cost 5269.85
------------------------------------------------
current join order:  [{'value': 'title', 'name': 't2'}, {'value': 'title', 'name': 't1'}, {'value': 'link_type', 'name': 'lt'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'keyword', 'name': 'k'}, {'value': 'movie_link', 'name': 'ml'}]
current join order cost:  5269.85
------------------------------------------------
------------------------------------------------
current join order:  [{'value': 'title', 'name': 't2'}, {'value': 'title', 'name': 't1'}, {'value': 'movie_link', 'name': 'ml'}, {'value': 'keyword', 'name': 'k'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'link_type', 'name': 'lt'}]
current join order cost:  5269.85
------------------------------------------------
------------------------------------------------
current join order:  [{'value': 'title', 'name': 't2'}, {'value': 'title', 'name': 't1'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'keyword', 'name': 'k'}, {'value': 'movie_link', 'name': 'ml'}, {'value': 'link_type', 'name': 'lt'}]
current join order cost:  5269.85
------------------------------------------------
------------------------------------------------
current join order:  [{'value': 'link_type', 'name': 'lt'}, {'value': 'movie_link', 'name': 'ml'}, {'value': 'keyword', 'name': 'k'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'title', 'name': 't1'}, {'value': 'title', 'name': 't2'}]
current join order cost:  5478.92
------------------------------------------------
------------------------------------------------
current join order:  [{'value': 'title', 'name': 't2'}, {'value': 'title', 'name': 't1'}, {'value': 'link_type', 'name': 'lt'}, {'value': 'movie_link', 'name': 'ml'}, {'value': 'keyword', 'name': 'k'}, {'value': 'movie_keyword', 'name': 'mk'}]
current join order cost:  5269.85
------------------------------------------------
------------------------------------------------
current join order:  [{'value': 'title', 'name': 't2'}, {'value': 'title', 'name': 't1'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'keyword', 'name': 'k'}, {'value': 'movie_link', 'name': 'ml'}, {'value': 'link_type', 'name': 'lt'}]
current join order cost:  5269.85
------------------------------------------------
------------------------------------------------
current join order:  [{'value': 'title', 'name': 't1'}, {'value': 'title', 'name': 't2'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'keyword', 'name': 'k'}, {'value': 'movie_link', 'name': 'ml'}, {'value': 'link_type', 'name': 'lt'}]
current join order cost:  5269.85
------------------------------------------------
solution_cost :  []
------------------------------------------------
current join order:  [{'value': 'cast_info', 'name': 'ci'}, {'value': 'company_name', 'name': 'cn'}, {'value': 'info_type', 'name': 'it1'}, {'value': 'info_type', 'name': 'it2'}, {'value': 'title', 'name': 't'}, {'value': 'name', 'name': 'n'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'movie_info_idx', 'name': 'mi_idx'}, {'value': 'movie_info', 'name': 'mi'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'keyword', 'name': 'k'}]
current join order cost:  8372.13
------------------------------------------------
best cost 8372.13
------------------------------------------------
current join order:  [{'value': 'cast_info', 'name': 'ci'}, {'value': 'title', 'name': 't'}, {'value': 'info_type', 'name': 'it2'}, {'value': 'info_type', 'name': 'it1'}, {'value': 'company_name', 'name': 'cn'}, {'value': 'name', 'name': 'n'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'movie_info_idx', 'name': 'mi_idx'}, {'value': 'movie_info', 'name': 'mi'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'keyword', 'name': 'k'}]
current join order cost:  8372.13
------------------------------------------------
------------------------------------------------
current join order:  [{'value': 'cast_info', 'name': 'ci'}, {'value': 'title', 'name': 't'}, {'value': 'info_type', 'name': 'it2'}, {'value': 'info_type', 'name': 'it1'}, {'value': 'company_name', 'name': 'cn'}, {'value': 'name', 'name': 'n'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'movie_info', 'name': 'mi'}, {'value': 'movie_info_idx', 'name': 'mi_idx'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'keyword', 'name': 'k'}]
current join order cost:  8372.13
------------------------------------------------
------------------------------------------------
current join order:  [{'value': 'cast_info', 'name': 'ci'}, {'value': 'title', 'name': 't'}, {'value': 'name', 'name': 'n'}, {'value': 'company_name', 'name': 'cn'}, {'value': 'info_type', 'name': 'it1'}, {'value': 'info_type', 'name': 'it2'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'movie_info', 'name': 'mi'}, {'value': 'movie_info_idx', 'name': 'mi_idx'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'keyword', 'name': 'k'}]
current join order cost:  8372.13
------------------------------------------------
------------------------------------------------
current join order:  [{'value': 'cast_info', 'name': 'ci'}, {'value': 'title', 'name': 't'}, {'value': 'keyword', 'name': 'k'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'movie_info_idx', 'name': 'mi_idx'}, {'value': 'movie_info', 'name': 'mi'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'info_type', 'name': 'it2'}, {'value': 'info_type', 'name': 'it1'}, {'value': 'company_name', 'name': 'cn'}, {'value': 'name', 'name': 'n'}]
current join order cost:  8372.13
------------------------------------------------
------------------------------------------------
current join order:  [{'value': 'cast_info', 'name': 'ci'}, {'value': 'company_name', 'name': 'cn'}, {'value': 'info_type', 'name': 'it1'}, {'value': 'info_type', 'name': 'it2'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'movie_info', 'name': 'mi'}, {'value': 'movie_info_idx', 'name': 'mi_idx'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'keyword', 'name': 'k'}, {'value': 'title', 'name': 't'}, {'value': 'name', 'name': 'n'}]
current join order cost:  8372.13
------------------------------------------------
------------------------------------------------
current join order:  [{'value': 'cast_info', 'name': 'ci'}, {'value': 'company_name', 'name': 'cn'}, {'value': 'info_type', 'name': 'it1'}, {'value': 'info_type', 'name': 'it2'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'movie_info', 'name': 'mi'}, {'value': 'movie_info_idx', 'name': 'mi_idx'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'keyword', 'name': 'k'}, {'value': 'name', 'name': 'n'}, {'value': 'title', 'name': 't'}]
current join order cost:  8372.13
------------------------------------------------
------------------------------------------------
current join order:  [{'value': 'cast_info', 'name': 'ci'}, {'value': 'company_name', 'name': 'cn'}, {'value': 'info_type', 'name': 'it1'}, {'value': 'movie_info', 'name': 'mi'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'info_type', 'name': 'it2'}, {'value': 'movie_info_idx', 'name': 'mi_idx'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'keyword', 'name': 'k'}, {'value': 'name', 'name': 'n'}, {'value': 'title', 'name': 't'}]
current join order cost:  8372.13
------------------------------------------------
------------------------------------------------
current join order:  [{'value': 'cast_info', 'name': 'ci'}, {'value': 'company_name', 'name': 'cn'}, {'value': 'info_type', 'name': 'it1'}, {'value': 'movie_info', 'name': 'mi'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'info_type', 'name': 'it2'}, {'value': 'movie_info_idx', 'name': 'mi_idx'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'name', 'name': 'n'}, {'value': 'keyword', 'name': 'k'}, {'value': 'title', 'name': 't'}]
current join order cost:  8372.13
------------------------------------------------
------------------------------------------------
current join order:  [{'value': 'cast_info', 'name': 'ci'}, {'value': 'company_name', 'name': 'cn'}, {'value': 'info_type', 'name': 'it1'}, {'value': 'movie_info', 'name': 'mi'}, {'value': 'movie_info_idx', 'name': 'mi_idx'}, {'value': 'info_type', 'name': 'it2'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'name', 'name': 'n'}, {'value': 'keyword', 'name': 'k'}, {'value': 'title', 'name': 't'}]
current join order cost:  8372.23
------------------------------------------------
solution_cost :  []
------------------------------------------------
current join order:  [{'value': 'aka_name', 'name': 'an'}, {'value': 'cast_info', 'name': 'ci'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'keyword', 'name': 'k'}, {'value': 'company_name', 'name': 'cn'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'name', 'name': 'n'}, {'value': 'title', 'name': 't'}]
current join order cost:  5574.87
------------------------------------------------
best cost 5574.87
------------------------------------------------
current join order:  [{'value': 'aka_name', 'name': 'an'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'cast_info', 'name': 'ci'}, {'value': 'keyword', 'name': 'k'}, {'value': 'company_name', 'name': 'cn'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'name', 'name': 'n'}, {'value': 'title', 'name': 't'}]
current join order cost:  5574.87
------------------------------------------------
------------------------------------------------
current join order:  [{'value': 'aka_name', 'name': 'an'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'cast_info', 'name': 'ci'}, {'value': 'keyword', 'name': 'k'}, {'value': 'title', 'name': 't'}, {'value': 'name', 'name': 'n'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'company_name', 'name': 'cn'}]
current join order cost:  5473.44
------------------------------------------------
best cost 5473.44
------------------------------------------------
current join order:  [{'value': 'aka_name', 'name': 'an'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'name', 'name': 'n'}, {'value': 'title', 'name': 't'}, {'value': 'keyword', 'name': 'k'}, {'value': 'cast_info', 'name': 'ci'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'company_name', 'name': 'cn'}]
current join order cost:  5317.22
------------------------------------------------
best cost 5317.22
------------------------------------------------
current join order:  [{'value': 'aka_name', 'name': 'an'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'cast_info', 'name': 'ci'}, {'value': 'keyword', 'name': 'k'}, {'value': 'title', 'name': 't'}, {'value': 'name', 'name': 'n'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'company_name', 'name': 'cn'}]
current join order cost:  5472.49
------------------------------------------------
------------------------------------------------
current join order:  [{'value': 'aka_name', 'name': 'an'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'name', 'name': 'n'}, {'value': 'title', 'name': 't'}, {'value': 'company_name', 'name': 'cn'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'cast_info', 'name': 'ci'}, {'value': 'keyword', 'name': 'k'}]
current join order cost:  5283.88
------------------------------------------------
best cost 5283.88
------------------------------------------------
current join order:  [{'value': 'aka_name', 'name': 'an'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'name', 'name': 'n'}, {'value': 'title', 'name': 't'}, {'value': 'keyword', 'name': 'k'}, {'value': 'cast_info', 'name': 'ci'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'company_name', 'name': 'cn'}]
current join order cost:  5317.22
------------------------------------------------
------------------------------------------------
current join order:  [{'value': 'company_name', 'name': 'cn'}, {'value': 'title', 'name': 't'}, {'value': 'name', 'name': 'n'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'aka_name', 'name': 'an'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'cast_info', 'name': 'ci'}, {'value': 'keyword', 'name': 'k'}]
current join order cost:  5281.4
------------------------------------------------
best cost 5281.4
------------------------------------------------
current join order:  [{'value': 'name', 'name': 'n'}, {'value': 'title', 'name': 't'}, {'value': 'company_name', 'name': 'cn'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'aka_name', 'name': 'an'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'cast_info', 'name': 'ci'}, {'value': 'keyword', 'name': 'k'}]
current join order cost:  5290.6
------------------------------------------------
------------------------------------------------
current join order:  [{'value': 'aka_name', 'name': 'an'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'name', 'name': 'n'}, {'value': 'title', 'name': 't'}, {'value': 'company_name', 'name': 'cn'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'cast_info', 'name': 'ci'}, {'value': 'keyword', 'name': 'k'}]
current join order cost:  5283.88
------------------------------------------------
solution_cost :  []
------------------------------------------------
current join order:  [{'value': 'aka_name', 'name': 'an'}, {'value': 'complete_cast', 'name': 'cc'}, {'value': 'comp_cast_type', 'name': 'cct1'}, {'value': 'keyword', 'name': 'k'}, {'value': 'info_type', 'name': 'it3'}, {'value': 'info_type', 'name': 'it'}, {'value': 'company_name', 'name': 'cn'}, {'value': 'cast_info', 'name': 'ci'}, {'value': 'char_name', 'name': 'chn'}, {'value': 'comp_cast_type', 'name': 'cct2'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'movie_info', 'name': 'mi'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'name', 'name': 'n'}, {'value': 'person_info', 'name': 'pi'}, {'value': 'role_type', 'name': 'rt'}, {'value': 'title', 'name': 't'}]
current join order cost:  5408.33
------------------------------------------------
------------------------------------------------
current join order:  [{'value': 'aka_name', 'name': 'an'}, {'value': 'complete_cast', 'name': 'cc'}, {'value': 'comp_cast_type', 'name': 'cct1'}, {'value': 'keyword', 'name': 'k'}, {'value': 'info_type', 'name': 'it3'}, {'value': 'info_type', 'name': 'it'}, {'value': 'company_name', 'name': 'cn'}, {'value': 'char_name', 'name': 'chn'}, {'value': 'cast_info', 'name': 'ci'}, {'value': 'comp_cast_type', 'name': 'cct2'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'movie_info', 'name': 'mi'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'name', 'name': 'n'}, {'value': 'person_info', 'name': 'pi'}, {'value': 'role_type', 'name': 'rt'}, {'value': 'title', 'name': 't'}]
current join order cost:  5406.31
------------------------------------------------
------------------------------------------------
current join order:  [{'value': 'aka_name', 'name': 'an'}, {'value': 'complete_cast', 'name': 'cc'}, {'value': 'name', 'name': 'n'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'movie_info', 'name': 'mi'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'comp_cast_type', 'name': 'cct2'}, {'value': 'cast_info', 'name': 'ci'}, {'value': 'char_name', 'name': 'chn'}, {'value': 'company_name', 'name': 'cn'}, {'value': 'info_type', 'name': 'it'}, {'value': 'info_type', 'name': 'it3'}, {'value': 'keyword', 'name': 'k'}, {'value': 'comp_cast_type', 'name': 'cct1'}, {'value': 'person_info', 'name': 'pi'}, {'value': 'role_type', 'name': 'rt'}, {'value': 'title', 'name': 't'}]
current join order cost:  5420.89
------------------------------------------------
------------------------------------------------
current join order:  [{'value': 'aka_name', 'name': 'an'}, {'value': 'comp_cast_type', 'name': 'cct1'}, {'value': 'complete_cast', 'name': 'cc'}, {'value': 'keyword', 'name': 'k'}, {'value': 'info_type', 'name': 'it3'}, {'value': 'info_type', 'name': 'it'}, {'value': 'company_name', 'name': 'cn'}, {'value': 'char_name', 'name': 'chn'}, {'value': 'cast_info', 'name': 'ci'}, {'value': 'comp_cast_type', 'name': 'cct2'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'movie_info', 'name': 'mi'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'name', 'name': 'n'}, {'value': 'person_info', 'name': 'pi'}, {'value': 'role_type', 'name': 'rt'}, {'value': 'title', 'name': 't'}]
current join order cost:  5406.31
------------------------------------------------
------------------------------------------------
current join order:  [{'value': 'aka_name', 'name': 'an'}, {'value': 'comp_cast_type', 'name': 'cct1'}, {'value': 'complete_cast', 'name': 'cc'}, {'value': 'keyword', 'name': 'k'}, {'value': 'info_type', 'name': 'it3'}, {'value': 'info_type', 'name': 'it'}, {'value': 'company_name', 'name': 'cn'}, {'value': 'char_name', 'name': 'chn'}, {'value': 'cast_info', 'name': 'ci'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'movie_info', 'name': 'mi'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'comp_cast_type', 'name': 'cct2'}, {'value': 'name', 'name': 'n'}, {'value': 'person_info', 'name': 'pi'}, {'value': 'role_type', 'name': 'rt'}, {'value': 'title', 'name': 't'}]
current join order cost:  5416.67
------------------------------------------------
------------------------------------------------
current join order:  [{'value': 'aka_name', 'name': 'an'}, {'value': 'comp_cast_type', 'name': 'cct1'}, {'value': 'complete_cast', 'name': 'cc'}, {'value': 'keyword', 'name': 'k'}, {'value': 'info_type', 'name': 'it3'}, {'value': 'company_name', 'name': 'cn'}, {'value': 'info_type', 'name': 'it'}, {'value': 'char_name', 'name': 'chn'}, {'value': 'cast_info', 'name': 'ci'}, {'value': 'comp_cast_type', 'name': 'cct2'}, {'value': 'movie_companies', 'name': 'mc'}, {'value': 'movie_info', 'name': 'mi'}, {'value': 'movie_keyword', 'name': 'mk'}, {'value': 'name', 'name': 'n'}, {'value': 'person_info', 'name': 'pi'}, {'value': 'role_type', 'name': 'rt'}, {'value': 'title', 'name': 't'}]
current join order cost:  5403.67
------------------------------------------------
best cost 5403.67
------------------------------------------------

KeyboardInterrupt: